// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AwsDeployment aws deployment
//
// swagger:model aws_deployment
type AwsDeployment struct {

	// byoip
	// Min Length: 1
	Byoip string `json:"byoip,omitempty"`

	// instance key
	// Min Length: 1
	InstanceKey string `json:"instance_key,omitempty"`

	// instance type
	// Min Length: 1
	InstanceType string `json:"instance_type,omitempty"`

	// private subnet
	// Min Length: 1
	PrivateSubnet string `json:"private_subnet,omitempty"`

	// private subnet route table
	// Min Length: 1
	PrivateSubnetRouteTable string `json:"private_subnet_route_table,omitempty"`

	// public subnet
	// Min Length: 1
	PublicSubnet string `json:"public_subnet,omitempty"`

	// region
	// Min Length: 1
	Region string `json:"region,omitempty"`

	// vpc id
	// Min Length: 1
	VpcID string `json:"vpc_id,omitempty"`
}

// Validate validates this aws deployment
func (m *AwsDeployment) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateByoip(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstanceKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstanceType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivateSubnet(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivateSubnetRouteTable(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicSubnet(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVpcID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AwsDeployment) validateByoip(formats strfmt.Registry) error {
	if swag.IsZero(m.Byoip) { // not required
		return nil
	}

	if err := validate.MinLength("byoip", "body", m.Byoip, 1); err != nil {
		return err
	}

	return nil
}

func (m *AwsDeployment) validateInstanceKey(formats strfmt.Registry) error {
	if swag.IsZero(m.InstanceKey) { // not required
		return nil
	}

	if err := validate.MinLength("instance_key", "body", m.InstanceKey, 1); err != nil {
		return err
	}

	return nil
}

func (m *AwsDeployment) validateInstanceType(formats strfmt.Registry) error {
	if swag.IsZero(m.InstanceType) { // not required
		return nil
	}

	if err := validate.MinLength("instance_type", "body", m.InstanceType, 1); err != nil {
		return err
	}

	return nil
}

func (m *AwsDeployment) validatePrivateSubnet(formats strfmt.Registry) error {
	if swag.IsZero(m.PrivateSubnet) { // not required
		return nil
	}

	if err := validate.MinLength("private_subnet", "body", m.PrivateSubnet, 1); err != nil {
		return err
	}

	return nil
}

func (m *AwsDeployment) validatePrivateSubnetRouteTable(formats strfmt.Registry) error {
	if swag.IsZero(m.PrivateSubnetRouteTable) { // not required
		return nil
	}

	if err := validate.MinLength("private_subnet_route_table", "body", m.PrivateSubnetRouteTable, 1); err != nil {
		return err
	}

	return nil
}

func (m *AwsDeployment) validatePublicSubnet(formats strfmt.Registry) error {
	if swag.IsZero(m.PublicSubnet) { // not required
		return nil
	}

	if err := validate.MinLength("public_subnet", "body", m.PublicSubnet, 1); err != nil {
		return err
	}

	return nil
}

func (m *AwsDeployment) validateRegion(formats strfmt.Registry) error {
	if swag.IsZero(m.Region) { // not required
		return nil
	}

	if err := validate.MinLength("region", "body", m.Region, 1); err != nil {
		return err
	}

	return nil
}

func (m *AwsDeployment) validateVpcID(formats strfmt.Registry) error {
	if swag.IsZero(m.VpcID) { // not required
		return nil
	}

	if err := validate.MinLength("vpc_id", "body", m.VpcID, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this aws deployment based on context it is used
func (m *AwsDeployment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AwsDeployment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AwsDeployment) UnmarshalBinary(b []byte) error {
	var res AwsDeployment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
