// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OnpremDeployment onprem deployment
//
// swagger:model onprem_deployment
type OnpremDeployment struct {

	// base image
	// Min Length: 1
	BaseImage string `json:"base_image,omitempty"`

	// default gw
	// Min Length: 1
	DefaultGw string `json:"default_gw,omitempty"`

	// prefix
	Prefix string `json:"prefix,omitempty"`

	// private ip
	// Min Length: 1
	PrivateIP string `json:"private_ip,omitempty"`

	// public ip
	// Min Length: 1
	PublicIP string `json:"public_ip,omitempty"`

	// ssh psw
	SSHPsw string `json:"ssh_psw,omitempty"`

	// subnet mask
	SubnetMask int64 `json:"subnet_mask,omitempty"`

	// use pvt ip
	// Read Only: true
	UsePvtIP *bool `json:"use_pvt_ip,omitempty"`

	// vcpus
	Vcpus int64 `json:"vcpus,omitempty"`

	// vlan list
	VlanList []string `json:"vlan_list"`

	// vm count
	VMCount int64 `json:"vm_count,omitempty"`

	// vm memory
	VMMemory int64 `json:"vm_memory,omitempty"`
}

// Validate validates this onprem deployment
func (m *OnpremDeployment) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaseImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDefaultGw(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivateIP(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OnpremDeployment) validateBaseImage(formats strfmt.Registry) error {
	if swag.IsZero(m.BaseImage) { // not required
		return nil
	}

	if err := validate.MinLength("base_image", "body", m.BaseImage, 1); err != nil {
		return err
	}

	return nil
}

func (m *OnpremDeployment) validateDefaultGw(formats strfmt.Registry) error {
	if swag.IsZero(m.DefaultGw) { // not required
		return nil
	}

	if err := validate.MinLength("default_gw", "body", m.DefaultGw, 1); err != nil {
		return err
	}

	return nil
}

func (m *OnpremDeployment) validatePrivateIP(formats strfmt.Registry) error {
	if swag.IsZero(m.PrivateIP) { // not required
		return nil
	}

	if err := validate.MinLength("private_ip", "body", m.PrivateIP, 1); err != nil {
		return err
	}

	return nil
}

func (m *OnpremDeployment) validatePublicIP(formats strfmt.Registry) error {
	if swag.IsZero(m.PublicIP) { // not required
		return nil
	}

	if err := validate.MinLength("public_ip", "body", m.PublicIP, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this onprem deployment based on the context it is used
func (m *OnpremDeployment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUsePvtIP(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OnpremDeployment) contextValidateUsePvtIP(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "use_pvt_ip", "body", m.UsePvtIP); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OnpremDeployment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OnpremDeployment) UnmarshalBinary(b []byte) error {
	var res OnpremDeployment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
